# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist4meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='playlist4meta.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13playlist4meta.proto\"-\n\x0cListChecksum\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04sha1\x18\x04 \x01(\x0c\"\x80\x01\n\x0e\x44ownloadFormat\x12$\n\x05\x63odec\x18\x01 \x01(\x0e\x32\x15.DownloadFormat.Codec\"H\n\x05\x43odec\x12\x11\n\rCODEC_UNKNOWN\x10\x00\x12\x0e\n\nOGG_VORBIS\x10\x01\x12\x08\n\x04\x46LAC\x10\x02\x12\x12\n\x0eMPEG_1_LAYER_3\x10\x03\"\xf5\x01\n\x0eListAttributes\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07picture\x18\x03 \x01(\x0c\x12\x15\n\rcollaborative\x18\x04 \x01(\x08\x12\x13\n\x0bpl3_version\x18\x05 \x01(\t\x12\x18\n\x10\x64\x65leted_by_owner\x18\x06 \x01(\x08\x12 \n\x18restricted_collaborative\x18\x07 \x01(\x08\x12\x1c\n\x14\x64\x65precated_client_id\x18\x08 \x01(\x03\x12\x16\n\x0epublic_starred\x18\t \x01(\x08\x12\x11\n\tclient_id\x18\n \x01(\t\"\xeb\x01\n\x0eItemAttributes\x12\x10\n\x08\x61\x64\x64\x65\x64_by\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04seen\x18\x04 \x01(\x08\x12\x16\n\x0e\x64ownload_count\x18\x05 \x01(\x03\x12(\n\x0f\x64ownload_format\x18\x06 \x01(\x0b\x32\x0f.DownloadFormat\x12\x17\n\x0fsevendigital_id\x18\x07 \x01(\t\x12\x19\n\x11sevendigital_left\x18\x08 \x01(\x03\x12\x0f\n\x07seen_at\x18\t \x01(\x03\x12\x0e\n\x06public\x18\n \x01(\x08\"-\n\x0fStringAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"7\n\x10StringAttributes\x12#\n\tattribute\x18\x01 \x03(\x0b\x32\x10.StringAttribute')
)



_DOWNLOADFORMAT_CODEC = _descriptor.EnumDescriptor(
  name='Codec',
  full_name='DownloadFormat.Codec',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CODEC_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OGG_VORBIS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLAC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPEG_1_LAYER_3', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=127,
  serialized_end=199,
)
_sym_db.RegisterEnumDescriptor(_DOWNLOADFORMAT_CODEC)


_LISTCHECKSUM = _descriptor.Descriptor(
  name='ListChecksum',
  full_name='ListChecksum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ListChecksum.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='ListChecksum.sha1', index=1,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=68,
)


_DOWNLOADFORMAT = _descriptor.Descriptor(
  name='DownloadFormat',
  full_name='DownloadFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codec', full_name='DownloadFormat.codec', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DOWNLOADFORMAT_CODEC,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=199,
)


_LISTATTRIBUTES = _descriptor.Descriptor(
  name='ListAttributes',
  full_name='ListAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ListAttributes.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='ListAttributes.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='picture', full_name='ListAttributes.picture', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collaborative', full_name='ListAttributes.collaborative', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pl3_version', full_name='ListAttributes.pl3_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted_by_owner', full_name='ListAttributes.deleted_by_owner', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restricted_collaborative', full_name='ListAttributes.restricted_collaborative', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_client_id', full_name='ListAttributes.deprecated_client_id', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_starred', full_name='ListAttributes.public_starred', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ListAttributes.client_id', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=447,
)


_ITEMATTRIBUTES = _descriptor.Descriptor(
  name='ItemAttributes',
  full_name='ItemAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='added_by', full_name='ItemAttributes.added_by', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ItemAttributes.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='ItemAttributes.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seen', full_name='ItemAttributes.seen', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='download_count', full_name='ItemAttributes.download_count', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='download_format', full_name='ItemAttributes.download_format', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sevendigital_id', full_name='ItemAttributes.sevendigital_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sevendigital_left', full_name='ItemAttributes.sevendigital_left', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seen_at', full_name='ItemAttributes.seen_at', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public', full_name='ItemAttributes.public', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=685,
)


_STRINGATTRIBUTE = _descriptor.Descriptor(
  name='StringAttribute',
  full_name='StringAttribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StringAttribute.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='StringAttribute.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=732,
)


_STRINGATTRIBUTES = _descriptor.Descriptor(
  name='StringAttributes',
  full_name='StringAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute', full_name='StringAttributes.attribute', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=789,
)

_DOWNLOADFORMAT.fields_by_name['codec'].enum_type = _DOWNLOADFORMAT_CODEC
_DOWNLOADFORMAT_CODEC.containing_type = _DOWNLOADFORMAT
_ITEMATTRIBUTES.fields_by_name['download_format'].message_type = _DOWNLOADFORMAT
_STRINGATTRIBUTES.fields_by_name['attribute'].message_type = _STRINGATTRIBUTE
DESCRIPTOR.message_types_by_name['ListChecksum'] = _LISTCHECKSUM
DESCRIPTOR.message_types_by_name['DownloadFormat'] = _DOWNLOADFORMAT
DESCRIPTOR.message_types_by_name['ListAttributes'] = _LISTATTRIBUTES
DESCRIPTOR.message_types_by_name['ItemAttributes'] = _ITEMATTRIBUTES
DESCRIPTOR.message_types_by_name['StringAttribute'] = _STRINGATTRIBUTE
DESCRIPTOR.message_types_by_name['StringAttributes'] = _STRINGATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListChecksum = _reflection.GeneratedProtocolMessageType('ListChecksum', (_message.Message,), dict(
  DESCRIPTOR = _LISTCHECKSUM,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:ListChecksum)
  ))
_sym_db.RegisterMessage(ListChecksum)

DownloadFormat = _reflection.GeneratedProtocolMessageType('DownloadFormat', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLOADFORMAT,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:DownloadFormat)
  ))
_sym_db.RegisterMessage(DownloadFormat)

ListAttributes = _reflection.GeneratedProtocolMessageType('ListAttributes', (_message.Message,), dict(
  DESCRIPTOR = _LISTATTRIBUTES,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:ListAttributes)
  ))
_sym_db.RegisterMessage(ListAttributes)

ItemAttributes = _reflection.GeneratedProtocolMessageType('ItemAttributes', (_message.Message,), dict(
  DESCRIPTOR = _ITEMATTRIBUTES,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:ItemAttributes)
  ))
_sym_db.RegisterMessage(ItemAttributes)

StringAttribute = _reflection.GeneratedProtocolMessageType('StringAttribute', (_message.Message,), dict(
  DESCRIPTOR = _STRINGATTRIBUTE,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:StringAttribute)
  ))
_sym_db.RegisterMessage(StringAttribute)

StringAttributes = _reflection.GeneratedProtocolMessageType('StringAttributes', (_message.Message,), dict(
  DESCRIPTOR = _STRINGATTRIBUTES,
  __module__ = 'playlist4meta_pb2'
  # @@protoc_insertion_point(class_scope:StringAttributes)
  ))
_sym_db.RegisterMessage(StringAttributes)


# @@protoc_insertion_point(module_scope)
