# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist4content.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import playlist4meta_pb2 as playlist4meta__pb2
import playlist4issues_pb2 as playlist4issues__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='playlist4content.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16playlist4content.proto\x1a\x13playlist4meta.proto\x1a\x15playlist4issues.proto\"8\n\x04Item\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12#\n\nattributes\x18\x02 \x01(\x0b\x32\x0f.ItemAttributes\"A\n\tListItems\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x11\n\ttruncated\x18\x02 \x01(\x08\x12\x14\n\x05items\x18\x03 \x03(\x0b\x32\x05.Item\"+\n\x0c\x43ontentRange\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\xeb\x02\n\x14ListContentSelection\x12\x14\n\x0cwantRevision\x18\x01 \x01(\x08\x12\x12\n\nwantLength\x18\x02 \x01(\x08\x12\x16\n\x0ewantAttributes\x18\x03 \x01(\x08\x12\x14\n\x0cwantChecksum\x18\x04 \x01(\x08\x12\x13\n\x0bwantContent\x18\x05 \x01(\x08\x12#\n\x0c\x63ontentRange\x18\x06 \x01(\x0b\x32\r.ContentRange\x12\x10\n\x08wantDiff\x18\x07 \x01(\x08\x12\x14\n\x0c\x62\x61seRevision\x18\x08 \x01(\x0c\x12\x14\n\x0chintRevision\x18\t \x01(\x0c\x12\x1d\n\x15wantNothingIfUpToDate\x18\n \x01(\x08\x12\x19\n\x11wantResolveAction\x18\x0c \x01(\x08\x12\x1c\n\x06issues\x18\r \x03(\x0b\x32\x0c.ClientIssue\x12+\n\rresolveAction\x18\x0e \x03(\x0b\x32\x14.ClientResolveAction')
  ,
  dependencies=[playlist4meta__pb2.DESCRIPTOR,playlist4issues__pb2.DESCRIPTOR,])




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='Item.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='Item.attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=126,
)


_LISTITEMS = _descriptor.Descriptor(
  name='ListItems',
  full_name='ListItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='ListItems.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truncated', full_name='ListItems.truncated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='ListItems.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=193,
)


_CONTENTRANGE = _descriptor.Descriptor(
  name='ContentRange',
  full_name='ContentRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='ContentRange.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='ContentRange.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=238,
)


_LISTCONTENTSELECTION = _descriptor.Descriptor(
  name='ListContentSelection',
  full_name='ListContentSelection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wantRevision', full_name='ListContentSelection.wantRevision', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantLength', full_name='ListContentSelection.wantLength', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantAttributes', full_name='ListContentSelection.wantAttributes', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantChecksum', full_name='ListContentSelection.wantChecksum', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantContent', full_name='ListContentSelection.wantContent', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contentRange', full_name='ListContentSelection.contentRange', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantDiff', full_name='ListContentSelection.wantDiff', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseRevision', full_name='ListContentSelection.baseRevision', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hintRevision', full_name='ListContentSelection.hintRevision', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantNothingIfUpToDate', full_name='ListContentSelection.wantNothingIfUpToDate', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wantResolveAction', full_name='ListContentSelection.wantResolveAction', index=10,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='issues', full_name='ListContentSelection.issues', index=11,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resolveAction', full_name='ListContentSelection.resolveAction', index=12,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=604,
)

_ITEM.fields_by_name['attributes'].message_type = playlist4meta__pb2._ITEMATTRIBUTES
_LISTITEMS.fields_by_name['items'].message_type = _ITEM
_LISTCONTENTSELECTION.fields_by_name['contentRange'].message_type = _CONTENTRANGE
_LISTCONTENTSELECTION.fields_by_name['issues'].message_type = playlist4issues__pb2._CLIENTISSUE
_LISTCONTENTSELECTION.fields_by_name['resolveAction'].message_type = playlist4issues__pb2._CLIENTRESOLVEACTION
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['ListItems'] = _LISTITEMS
DESCRIPTOR.message_types_by_name['ContentRange'] = _CONTENTRANGE
DESCRIPTOR.message_types_by_name['ListContentSelection'] = _LISTCONTENTSELECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'playlist4content_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  ))
_sym_db.RegisterMessage(Item)

ListItems = _reflection.GeneratedProtocolMessageType('ListItems', (_message.Message,), dict(
  DESCRIPTOR = _LISTITEMS,
  __module__ = 'playlist4content_pb2'
  # @@protoc_insertion_point(class_scope:ListItems)
  ))
_sym_db.RegisterMessage(ListItems)

ContentRange = _reflection.GeneratedProtocolMessageType('ContentRange', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTRANGE,
  __module__ = 'playlist4content_pb2'
  # @@protoc_insertion_point(class_scope:ContentRange)
  ))
_sym_db.RegisterMessage(ContentRange)

ListContentSelection = _reflection.GeneratedProtocolMessageType('ListContentSelection', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONTENTSELECTION,
  __module__ = 'playlist4content_pb2'
  # @@protoc_insertion_point(class_scope:ListContentSelection)
  ))
_sym_db.RegisterMessage(ListContentSelection)


# @@protoc_insertion_point(module_scope)
